# coding: utf-8

"""
    Read-only API для онлайн-кинотеатра

    Информация о фильмах, жанрах и людях, участвовавших в создании произведения  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FullPerson(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uuid': 'str',
        'full_name': 'str',
        'role': 'AnyOfFullPersonRole',
        'film_ids': 'list[str]'
    }

    attribute_map = {
        'uuid': 'uuid',
        'full_name': 'full_name',
        'role': 'role',
        'film_ids': 'film_ids'
    }

    def __init__(self, uuid=None, full_name=None, role=None, film_ids=None):  # noqa: E501
        """FullPerson - a model defined in Swagger"""  # noqa: E501
        self._uuid = None
        self._full_name = None
        self._role = None
        self._film_ids = None
        self.discriminator = None
        self.uuid = uuid
        self.full_name = full_name
        if role is not None:
            self.role = role
        if film_ids is not None:
            self.film_ids = film_ids

    @property
    def uuid(self):
        """Gets the uuid of this FullPerson.  # noqa: E501


        :return: The uuid of this FullPerson.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this FullPerson.


        :param uuid: The uuid of this FullPerson.  # noqa: E501
        :type: str
        """
        if uuid is None:
            raise ValueError("Invalid value for `uuid`, must not be `None`")  # noqa: E501

        self._uuid = uuid

    @property
    def full_name(self):
        """Gets the full_name of this FullPerson.  # noqa: E501


        :return: The full_name of this FullPerson.  # noqa: E501
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name):
        """Sets the full_name of this FullPerson.


        :param full_name: The full_name of this FullPerson.  # noqa: E501
        :type: str
        """
        if full_name is None:
            raise ValueError("Invalid value for `full_name`, must not be `None`")  # noqa: E501

        self._full_name = full_name

    @property
    def role(self):
        """Gets the role of this FullPerson.  # noqa: E501


        :return: The role of this FullPerson.  # noqa: E501
        :rtype: AnyOfFullPersonRole
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this FullPerson.


        :param role: The role of this FullPerson.  # noqa: E501
        :type: AnyOfFullPersonRole
        """

        self._role = role

    @property
    def film_ids(self):
        """Gets the film_ids of this FullPerson.  # noqa: E501


        :return: The film_ids of this FullPerson.  # noqa: E501
        :rtype: list[str]
        """
        return self._film_ids

    @film_ids.setter
    def film_ids(self, film_ids):
        """Sets the film_ids of this FullPerson.


        :param film_ids: The film_ids of this FullPerson.  # noqa: E501
        :type: list[str]
        """

        self._film_ids = film_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FullPerson, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FullPerson):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
