# coding: utf-8

"""
    Read-only API для онлайн-кинотеатра

    Информация о фильмах, жанрах и людях, участвовавших в создании произведения  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.film import Film  # noqa: E501
from swagger_client.rest import ApiException


class TestFilm(unittest.TestCase):
    """Film unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilm(self):
        """Test Film"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.film.Film()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
