# coding: utf-8

"""
    Read-only API для онлайн-кинотеатра

    Информация о фильмах, жанрах и людях, участвовавших в создании произведения  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import content
from content.models.person import Person  # noqa: E501
from content.rest import ApiException


class TestPerson(unittest.TestCase):
    """Person unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPerson(self):
        """Test Person"""
        # FIXME: construct object with mandatory attributes with example values
        # model = content.models.person.Person()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
