# coding: utf-8

"""
    Read-only API для онлайн-кинотеатра

    Информация о фильмах, жанрах и людях, участвовавших в создании произведения  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import content
from content.api.health_api import HealthApi  # noqa: E501
from content.rest import ApiException


class TestHealthApi(unittest.TestCase):
    """HealthApi unit test stubs"""

    def setUp(self):
        self.api = HealthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_health_check_content_api_api_health_get(self):
        """Test case for health_check_content_api_api_health_get

        Health Check  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
