# coding: utf-8

"""
    Read-only API для онлайн-кинотеатра

    Информация о фильмах, жанрах и людях, участвовавших в создании произведения  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.__api import _Api  # noqa: E501
from swagger_client.rest import ApiException


class Test_Api(unittest.TestCase):
    """_Api unit test stubs"""

    def setUp(self):
        self.api = _Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_search_films_content_api_api_v1_film_search_get(self):
        """Test case for search_films_content_api_api_v1_film_search_get

        Поиск кинопроизведений  # noqa: E501
        """
        pass

    def test_search_persons_content_api_api_v1_person_search_get(self):
        """Test case for search_persons_content_api_api_v1_person_search_get

        Поиск по людям  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
