# coding: utf-8

"""
    Read-only API для онлайн-кинотеатра

    Информация о фильмах, жанрах и людях, участвовавших в создании произведения  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.any_of_full_person_role import AnyOfFullPersonRole  # noqa: E501
from swagger_client.rest import ApiException


class TestAnyOfFullPersonRole(unittest.TestCase):
    """AnyOfFullPersonRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyOfFullPersonRole(self):
        """Test AnyOfFullPersonRole"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.any_of_full_person_role.AnyOfFullPersonRole()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
