# coding: utf-8

"""
    Read-only API для онлайн-кинотеатра

    Информация о фильмах, жанрах и людях, участвовавших в создании произведения  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import content
from content.models.film_detail import FilmDetail  # noqa: E501
from content.rest import ApiException


class TestFilmDetail(unittest.TestCase):
    """FilmDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilmDetail(self):
        """Test FilmDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = content.models.film_detail.FilmDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
