# coding: utf-8

"""
    Read-only API для онлайн-кинотеатра

    Информация о фильмах, жанрах и людях, участвовавших в создании произведения  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.genre import Genre  # noqa: E501
from swagger_client.rest import ApiException


class TestGenre(unittest.TestCase):
    """Genre unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenre(self):
        """Test Genre"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.genre.Genre()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
