# coding: utf-8

"""
    Read-only API для онлайн-кинотеатра

    Информация о фильмах, жанрах и людях, участвовавших в создании произведения  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import content
from content.api.default_api import DefaultApi  # noqa: E501
from content.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_film_details_content_api_api_v1_film_film_id_get(self):
        """Test case for film_details_content_api_api_v1_film_film_id_get

        Кинопроизведение  # noqa: E501
        """
        pass

    def test_film_details_content_api_api_v1_film_film_id_get_0(self):
        """Test case for film_details_content_api_api_v1_film_film_id_get_0

        Кинопроизведение  # noqa: E501
        """
        pass

    def test_films_list_content_api_api_v1_film_get(self):
        """Test case for films_list_content_api_api_v1_film_get

        Кинопроизведения  # noqa: E501
        """
        pass

    def test_films_list_content_api_api_v1_film_get_0(self):
        """Test case for films_list_content_api_api_v1_film_get_0

        Кинопроизведения  # noqa: E501
        """
        pass

    def test_genres_content_api_api_v1_genre_genre_id_get(self):
        """Test case for genres_content_api_api_v1_genre_genre_id_get

        Жанр  # noqa: E501
        """
        pass

    def test_genres_content_api_api_v1_genre_genre_id_get_0(self):
        """Test case for genres_content_api_api_v1_genre_genre_id_get_0

        Жанр  # noqa: E501
        """
        pass

    def test_genres_content_api_api_v1_genre_get(self):
        """Test case for genres_content_api_api_v1_genre_get

        Жанры кинопроизведений  # noqa: E501
        """
        pass

    def test_genres_content_api_api_v1_genre_get_0(self):
        """Test case for genres_content_api_api_v1_genre_get_0

        Жанры кинопроизведений  # noqa: E501
        """
        pass

    def test_get_person_content_api_api_v1_person_person_id_get(self):
        """Test case for get_person_content_api_api_v1_person_person_id_get

        Детальное описание человека  # noqa: E501
        """
        pass

    def test_get_person_content_api_api_v1_person_person_id_get_0(self):
        """Test case for get_person_content_api_api_v1_person_person_id_get_0

        Детальное описание человека  # noqa: E501
        """
        pass

    def test_get_person_film_content_api_api_v1_person_person_id_film_get(self):
        """Test case for get_person_film_content_api_api_v1_person_person_id_film_get

        Фильмы человека  # noqa: E501
        """
        pass

    def test_get_person_film_content_api_api_v1_person_person_id_film_get_0(self):
        """Test case for get_person_film_content_api_api_v1_person_person_id_film_get_0

        Фильмы человека  # noqa: E501
        """
        pass

    def test_search_films_content_api_api_v1_film_search_get(self):
        """Test case for search_films_content_api_api_v1_film_search_get

        Поиск кинопроизведений  # noqa: E501
        """
        pass

    def test_search_persons_content_api_api_v1_person_search_get(self):
        """Test case for search_persons_content_api_api_v1_person_search_get

        Поиск по людям  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
