# coding: utf-8

"""
    Read-only API для онлайн-кинотеатра

    Информация о фильмах, жанрах и людях, участвовавших в создании произведения  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from content_api.api_client import ApiClient


class DefaultApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def film_details_content_api_api_v1_film_film_id_get(self, film_id, **kwargs):  # noqa: E501
        """Кинопроизведение  # noqa: E501

        Детальное описание кинопроизведения  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.film_details_content_api_api_v1_film_film_id_get(film_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str film_id: (required)
        :return: FilmDetail
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.film_details_content_api_api_v1_film_film_id_get_with_http_info(film_id, **kwargs)  # noqa: E501
        else:
            (data) = self.film_details_content_api_api_v1_film_film_id_get_with_http_info(film_id, **kwargs)  # noqa: E501
            return data

    def film_details_content_api_api_v1_film_film_id_get_with_http_info(self, film_id, **kwargs):  # noqa: E501
        """Кинопроизведение  # noqa: E501

        Детальное описание кинопроизведения  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.film_details_content_api_api_v1_film_film_id_get_with_http_info(film_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str film_id: (required)
        :return: FilmDetail
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['film_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method film_details_content_api_api_v1_film_film_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'film_id' is set
        if ('film_id' not in params or
                params['film_id'] is None):
            raise ValueError("Missing the required parameter `film_id` when calling `film_details_content_api_api_v1_film_film_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'film_id' in params:
            path_params['film_id'] = params['film_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/content_api/api/v1/film/{film_id}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='FilmDetail',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def film_details_content_api_api_v1_film_film_id_get_0(self, film_id, **kwargs):  # noqa: E501
        """Кинопроизведение  # noqa: E501

        Детальное описание кинопроизведения  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.film_details_content_api_api_v1_film_film_id_get_0(film_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str film_id: (required)
        :return: FilmDetail
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.film_details_content_api_api_v1_film_film_id_get_0_with_http_info(film_id, **kwargs)  # noqa: E501
        else:
            (data) = self.film_details_content_api_api_v1_film_film_id_get_0_with_http_info(film_id, **kwargs)  # noqa: E501
            return data

    def film_details_content_api_api_v1_film_film_id_get_0_with_http_info(self, film_id, **kwargs):  # noqa: E501
        """Кинопроизведение  # noqa: E501

        Детальное описание кинопроизведения  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.film_details_content_api_api_v1_film_film_id_get_0_with_http_info(film_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str film_id: (required)
        :return: FilmDetail
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['film_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method film_details_content_api_api_v1_film_film_id_get_0" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'film_id' is set
        if ('film_id' not in params or
                params['film_id'] is None):
            raise ValueError("Missing the required parameter `film_id` when calling `film_details_content_api_api_v1_film_film_id_get_0`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'film_id' in params:
            path_params['film_id'] = params['film_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/content_api/api/v1/film/{film_id}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='FilmDetail',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def films_list_content_api_api_v1_film_get(self, **kwargs):  # noqa: E501
        """Кинопроизведения  # noqa: E501

        Список кинопроизведений с соритровкой, отборами и пагинацией  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.films_list_content_api_api_v1_film_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str filter_genre: filter on genre
        :param str sort: sort on filed (order: \"-\" before filed name is desc)
        :param int page_size: Page size
        :param int page_number: Page number
        :return: list[Film]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.films_list_content_api_api_v1_film_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.films_list_content_api_api_v1_film_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def films_list_content_api_api_v1_film_get_with_http_info(self, **kwargs):  # noqa: E501
        """Кинопроизведения  # noqa: E501

        Список кинопроизведений с соритровкой, отборами и пагинацией  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.films_list_content_api_api_v1_film_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str filter_genre: filter on genre
        :param str sort: sort on filed (order: \"-\" before filed name is desc)
        :param int page_size: Page size
        :param int page_number: Page number
        :return: list[Film]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['filter_genre', 'sort', 'page_size', 'page_number']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method films_list_content_api_api_v1_film_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'filter_genre' in params:
            query_params.append(('filter[genre]', params['filter_genre']))  # noqa: E501
        if 'sort' in params:
            query_params.append(('sort', params['sort']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page[size]', params['page_size']))  # noqa: E501
        if 'page_number' in params:
            query_params.append(('page[number]', params['page_number']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/content_api/api/v1/film/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Film]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def films_list_content_api_api_v1_film_get_0(self, **kwargs):  # noqa: E501
        """Кинопроизведения  # noqa: E501

        Список кинопроизведений с соритровкой, отборами и пагинацией  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.films_list_content_api_api_v1_film_get_0(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str filter_genre: filter on genre
        :param str sort: sort on filed (order: \"-\" before filed name is desc)
        :param int page_size: Page size
        :param int page_number: Page number
        :return: list[Film]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.films_list_content_api_api_v1_film_get_0_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.films_list_content_api_api_v1_film_get_0_with_http_info(**kwargs)  # noqa: E501
            return data

    def films_list_content_api_api_v1_film_get_0_with_http_info(self, **kwargs):  # noqa: E501
        """Кинопроизведения  # noqa: E501

        Список кинопроизведений с соритровкой, отборами и пагинацией  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.films_list_content_api_api_v1_film_get_0_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str filter_genre: filter on genre
        :param str sort: sort on filed (order: \"-\" before filed name is desc)
        :param int page_size: Page size
        :param int page_number: Page number
        :return: list[Film]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['filter_genre', 'sort', 'page_size', 'page_number']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method films_list_content_api_api_v1_film_get_0" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'filter_genre' in params:
            query_params.append(('filter[genre]', params['filter_genre']))  # noqa: E501
        if 'sort' in params:
            query_params.append(('sort', params['sort']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page[size]', params['page_size']))  # noqa: E501
        if 'page_number' in params:
            query_params.append(('page[number]', params['page_number']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/content_api/api/v1/film/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Film]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def genres_content_api_api_v1_genre_genre_id_get(self, genre_id, **kwargs):  # noqa: E501
        """Жанр  # noqa: E501

        Описание конкретного кинопроизведения  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.genres_content_api_api_v1_genre_genre_id_get(genre_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str genre_id: (required)
        :return: Genre
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.genres_content_api_api_v1_genre_genre_id_get_with_http_info(genre_id, **kwargs)  # noqa: E501
        else:
            (data) = self.genres_content_api_api_v1_genre_genre_id_get_with_http_info(genre_id, **kwargs)  # noqa: E501
            return data

    def genres_content_api_api_v1_genre_genre_id_get_with_http_info(self, genre_id, **kwargs):  # noqa: E501
        """Жанр  # noqa: E501

        Описание конкретного кинопроизведения  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.genres_content_api_api_v1_genre_genre_id_get_with_http_info(genre_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str genre_id: (required)
        :return: Genre
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['genre_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method genres_content_api_api_v1_genre_genre_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'genre_id' is set
        if ('genre_id' not in params or
                params['genre_id'] is None):
            raise ValueError("Missing the required parameter `genre_id` when calling `genres_content_api_api_v1_genre_genre_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'genre_id' in params:
            path_params['genre_id'] = params['genre_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/content_api/api/v1/genre/{genre_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Genre',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def genres_content_api_api_v1_genre_genre_id_get_0(self, genre_id, **kwargs):  # noqa: E501
        """Жанр  # noqa: E501

        Описание конкретного кинопроизведения  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.genres_content_api_api_v1_genre_genre_id_get_0(genre_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str genre_id: (required)
        :return: Genre
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.genres_content_api_api_v1_genre_genre_id_get_0_with_http_info(genre_id, **kwargs)  # noqa: E501
        else:
            (data) = self.genres_content_api_api_v1_genre_genre_id_get_0_with_http_info(genre_id, **kwargs)  # noqa: E501
            return data

    def genres_content_api_api_v1_genre_genre_id_get_0_with_http_info(self, genre_id, **kwargs):  # noqa: E501
        """Жанр  # noqa: E501

        Описание конкретного кинопроизведения  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.genres_content_api_api_v1_genre_genre_id_get_0_with_http_info(genre_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str genre_id: (required)
        :return: Genre
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['genre_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method genres_content_api_api_v1_genre_genre_id_get_0" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'genre_id' is set
        if ('genre_id' not in params or
                params['genre_id'] is None):
            raise ValueError("Missing the required parameter `genre_id` when calling `genres_content_api_api_v1_genre_genre_id_get_0`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'genre_id' in params:
            path_params['genre_id'] = params['genre_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/content_api/api/v1/genre/{genre_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Genre',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def genres_content_api_api_v1_genre_get(self, **kwargs):  # noqa: E501
        """Жанры кинопроизведений  # noqa: E501

        Список жанров кинопроизведений  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.genres_content_api_api_v1_genre_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str sort: sort on filed (order: \"-\" before filed name is desc)
        :param int page_size: Page size
        :param int page_number: Page number
        :return: list[Genre]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.genres_content_api_api_v1_genre_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.genres_content_api_api_v1_genre_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def genres_content_api_api_v1_genre_get_with_http_info(self, **kwargs):  # noqa: E501
        """Жанры кинопроизведений  # noqa: E501

        Список жанров кинопроизведений  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.genres_content_api_api_v1_genre_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str sort: sort on filed (order: \"-\" before filed name is desc)
        :param int page_size: Page size
        :param int page_number: Page number
        :return: list[Genre]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['sort', 'page_size', 'page_number']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method genres_content_api_api_v1_genre_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'sort' in params:
            query_params.append(('sort', params['sort']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page[size]', params['page_size']))  # noqa: E501
        if 'page_number' in params:
            query_params.append(('page[number]', params['page_number']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/content_api/api/v1/genre', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Genre]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def genres_content_api_api_v1_genre_get_0(self, **kwargs):  # noqa: E501
        """Жанры кинопроизведений  # noqa: E501

        Список жанров кинопроизведений  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.genres_content_api_api_v1_genre_get_0(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str sort: sort on filed (order: \"-\" before filed name is desc)
        :param int page_size: Page size
        :param int page_number: Page number
        :return: list[Genre]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.genres_content_api_api_v1_genre_get_0_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.genres_content_api_api_v1_genre_get_0_with_http_info(**kwargs)  # noqa: E501
            return data

    def genres_content_api_api_v1_genre_get_0_with_http_info(self, **kwargs):  # noqa: E501
        """Жанры кинопроизведений  # noqa: E501

        Список жанров кинопроизведений  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.genres_content_api_api_v1_genre_get_0_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str sort: sort on filed (order: \"-\" before filed name is desc)
        :param int page_size: Page size
        :param int page_number: Page number
        :return: list[Genre]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['sort', 'page_size', 'page_number']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method genres_content_api_api_v1_genre_get_0" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'sort' in params:
            query_params.append(('sort', params['sort']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page[size]', params['page_size']))  # noqa: E501
        if 'page_number' in params:
            query_params.append(('page[number]', params['page_number']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/content_api/api/v1/genre', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Genre]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_person_content_api_api_v1_person_person_id_get(self, person_id, **kwargs):  # noqa: E501
        """Детальное описание человека  # noqa: E501

        Полная информация по человеку на основании его id  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_person_content_api_api_v1_person_person_id_get(person_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str person_id: (required)
        :return: FullPerson
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_person_content_api_api_v1_person_person_id_get_with_http_info(person_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_person_content_api_api_v1_person_person_id_get_with_http_info(person_id, **kwargs)  # noqa: E501
            return data

    def get_person_content_api_api_v1_person_person_id_get_with_http_info(self, person_id, **kwargs):  # noqa: E501
        """Детальное описание человека  # noqa: E501

        Полная информация по человеку на основании его id  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_person_content_api_api_v1_person_person_id_get_with_http_info(person_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str person_id: (required)
        :return: FullPerson
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['person_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_person_content_api_api_v1_person_person_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'person_id' is set
        if ('person_id' not in params or
                params['person_id'] is None):
            raise ValueError("Missing the required parameter `person_id` when calling `get_person_content_api_api_v1_person_person_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'person_id' in params:
            path_params['person_id'] = params['person_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/content_api/api/v1/person/{person_id}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='FullPerson',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_person_content_api_api_v1_person_person_id_get_0(self, person_id, **kwargs):  # noqa: E501
        """Детальное описание человека  # noqa: E501

        Полная информация по человеку на основании его id  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_person_content_api_api_v1_person_person_id_get_0(person_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str person_id: (required)
        :return: FullPerson
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_person_content_api_api_v1_person_person_id_get_0_with_http_info(person_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_person_content_api_api_v1_person_person_id_get_0_with_http_info(person_id, **kwargs)  # noqa: E501
            return data

    def get_person_content_api_api_v1_person_person_id_get_0_with_http_info(self, person_id, **kwargs):  # noqa: E501
        """Детальное описание человека  # noqa: E501

        Полная информация по человеку на основании его id  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_person_content_api_api_v1_person_person_id_get_0_with_http_info(person_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str person_id: (required)
        :return: FullPerson
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['person_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_person_content_api_api_v1_person_person_id_get_0" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'person_id' is set
        if ('person_id' not in params or
                params['person_id'] is None):
            raise ValueError("Missing the required parameter `person_id` when calling `get_person_content_api_api_v1_person_person_id_get_0`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'person_id' in params:
            path_params['person_id'] = params['person_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/content_api/api/v1/person/{person_id}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='FullPerson',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_person_film_content_api_api_v1_person_person_id_film_get(self, person_id, **kwargs):  # noqa: E501
        """Фильмы человека  # noqa: E501

        Информация фильмах, в которых учавствовал человек  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_person_film_content_api_api_v1_person_person_id_film_get(person_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str person_id: (required)
        :param int page_size: Page size
        :param int page_number: Page number
        :return: list[Film]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_person_film_content_api_api_v1_person_person_id_film_get_with_http_info(person_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_person_film_content_api_api_v1_person_person_id_film_get_with_http_info(person_id, **kwargs)  # noqa: E501
            return data

    def get_person_film_content_api_api_v1_person_person_id_film_get_with_http_info(self, person_id, **kwargs):  # noqa: E501
        """Фильмы человека  # noqa: E501

        Информация фильмах, в которых учавствовал человек  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_person_film_content_api_api_v1_person_person_id_film_get_with_http_info(person_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str person_id: (required)
        :param int page_size: Page size
        :param int page_number: Page number
        :return: list[Film]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['person_id', 'page_size', 'page_number']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_person_film_content_api_api_v1_person_person_id_film_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'person_id' is set
        if ('person_id' not in params or
                params['person_id'] is None):
            raise ValueError("Missing the required parameter `person_id` when calling `get_person_film_content_api_api_v1_person_person_id_film_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'person_id' in params:
            path_params['person_id'] = params['person_id']  # noqa: E501

        query_params = []
        if 'page_size' in params:
            query_params.append(('page[size]', params['page_size']))  # noqa: E501
        if 'page_number' in params:
            query_params.append(('page[number]', params['page_number']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/content_api/api/v1/person/{person_id}/film/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Film]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_person_film_content_api_api_v1_person_person_id_film_get_0(self, person_id, **kwargs):  # noqa: E501
        """Фильмы человека  # noqa: E501

        Информация фильмах, в которых учавствовал человек  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_person_film_content_api_api_v1_person_person_id_film_get_0(person_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str person_id: (required)
        :param int page_size: Page size
        :param int page_number: Page number
        :return: list[Film]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_person_film_content_api_api_v1_person_person_id_film_get_0_with_http_info(person_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_person_film_content_api_api_v1_person_person_id_film_get_0_with_http_info(person_id, **kwargs)  # noqa: E501
            return data

    def get_person_film_content_api_api_v1_person_person_id_film_get_0_with_http_info(self, person_id, **kwargs):  # noqa: E501
        """Фильмы человека  # noqa: E501

        Информация фильмах, в которых учавствовал человек  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_person_film_content_api_api_v1_person_person_id_film_get_0_with_http_info(person_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str person_id: (required)
        :param int page_size: Page size
        :param int page_number: Page number
        :return: list[Film]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['person_id', 'page_size', 'page_number']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_person_film_content_api_api_v1_person_person_id_film_get_0" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'person_id' is set
        if ('person_id' not in params or
                params['person_id'] is None):
            raise ValueError("Missing the required parameter `person_id` when calling `get_person_film_content_api_api_v1_person_person_id_film_get_0`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'person_id' in params:
            path_params['person_id'] = params['person_id']  # noqa: E501

        query_params = []
        if 'page_size' in params:
            query_params.append(('page[size]', params['page_size']))  # noqa: E501
        if 'page_number' in params:
            query_params.append(('page[number]', params['page_number']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/content_api/api/v1/person/{person_id}/film/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Film]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def search_films_content_api_api_v1_film_search_get(self, query, **kwargs):  # noqa: E501
        """Поиск кинопроизведений  # noqa: E501

        Полнотекстовый поиск по кинопроизведениям  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_films_content_api_api_v1_film_search_get(query, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str query: search text_query (required)
        :param int page_size: Page size
        :param int page_number: Page number
        :return: list[Film]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.search_films_content_api_api_v1_film_search_get_with_http_info(query, **kwargs)  # noqa: E501
        else:
            (data) = self.search_films_content_api_api_v1_film_search_get_with_http_info(query, **kwargs)  # noqa: E501
            return data

    def search_films_content_api_api_v1_film_search_get_with_http_info(self, query, **kwargs):  # noqa: E501
        """Поиск кинопроизведений  # noqa: E501

        Полнотекстовый поиск по кинопроизведениям  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_films_content_api_api_v1_film_search_get_with_http_info(query, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str query: search text_query (required)
        :param int page_size: Page size
        :param int page_number: Page number
        :return: list[Film]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['query', 'page_size', 'page_number']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_films_content_api_api_v1_film_search_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'query' is set
        if ('query' not in params or
                params['query'] is None):
            raise ValueError("Missing the required parameter `query` when calling `search_films_content_api_api_v1_film_search_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'query' in params:
            query_params.append(('query', params['query']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page[size]', params['page_size']))  # noqa: E501
        if 'page_number' in params:
            query_params.append(('page[number]', params['page_number']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/content_api/api/v1/film/search/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Film]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def search_persons_content_api_api_v1_person_search_get(self, query, **kwargs):  # noqa: E501
        """Поиск по людям  # noqa: E501

        Полнотекстовый поиск по людям, учавствовшим в создании произведения  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_persons_content_api_api_v1_person_search_get(query, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str query: search text_query (required)
        :param int page_size: Page size
        :param int page_number: Page number
        :return: list[FullPerson]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.search_persons_content_api_api_v1_person_search_get_with_http_info(query, **kwargs)  # noqa: E501
        else:
            (data) = self.search_persons_content_api_api_v1_person_search_get_with_http_info(query, **kwargs)  # noqa: E501
            return data

    def search_persons_content_api_api_v1_person_search_get_with_http_info(self, query, **kwargs):  # noqa: E501
        """Поиск по людям  # noqa: E501

        Полнотекстовый поиск по людям, учавствовшим в создании произведения  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_persons_content_api_api_v1_person_search_get_with_http_info(query, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str query: search text_query (required)
        :param int page_size: Page size
        :param int page_number: Page number
        :return: list[FullPerson]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['query', 'page_size', 'page_number']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_persons_content_api_api_v1_person_search_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'query' is set
        if ('query' not in params or
                params['query'] is None):
            raise ValueError("Missing the required parameter `query` when calling `search_persons_content_api_api_v1_person_search_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'query' in params:
            query_params.append(('query', params['query']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page[size]', params['page_size']))  # noqa: E501
        if 'page_number' in params:
            query_params.append(('page[number]', params['page_number']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/content_api/api/v1/person/search/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[FullPerson]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
