# coding: utf-8

# flake8: noqa
"""
    Read-only API для онлайн-кинотеатра

    Информация о фильмах, жанрах и людях, участвовавших в создании произведения  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.any_of_full_person_role import AnyOfFullPersonRole
from swagger_client.models.film import Film
from swagger_client.models.film_detail import FilmDetail
from swagger_client.models.full_person import FullPerson
from swagger_client.models.genre import Genre
from swagger_client.models.http_validation_error import HTTPValidationError
from swagger_client.models.person import Person
from swagger_client.models.validation_error import ValidationError
